App\Entity\User:
  properties:
    email:
      - NotBlank: ~
      - Email: ~
    password:
      - NotBlank: ~
      - Length: { min: 6, max: 4096 }
    firstname:
      - NotBlank: ~
      - Length: { min: 2, max: 50 }
    lastname:
      - NotBlank: ~
      - Length: { min: 2, max: 50 }
    tel:
      - NotBlank: ~
      - Length: { min: 6, max: 20 }
      - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber: { defaultRegion: 'SR', message: 'validators.users.constraint.tel.phone_number' }
    locale:
      - Choice: { choices: ['en', 'hu', 'sr_Latn'] }
    captcha:
      - Karser\Recaptcha3Bundle\Validator\Constraints\Recaptcha3: { message: 'validators.users.constraint.captcha' }
    isVerified:
      - Choice: { choices: [true, false, 1, 0] }
    is_deleted:
      - Choice: { choices: [true, false, 1, 0] }

  getters:
    role:
      - 'IsTrue': { message: 'validators.users.constraint.role.invalid' }


App\Entity\Reservation:
  properties:
    user:
      - NotBlank: ~
    parcel_number:
      - NotBlank: ~
      - Positive: ~
    land_area:
      - NotBlank: ~
      - Positive: ~
    chemical:
      - NotBlank: ~
    is_deleted:
      - Choice: { choices: [true, false, 1, 0] }
    # -1: non-active, 0: pending, 1: in process
    status:
      - Choice: { choices: [0, 1, 2] }
    to_be_present:
      - Choice: { choices: [true, false, 1, 0] }
    comment:
      - Length: { max: 5000 }
    plant:
      - NotBlank: ~


App\Entity\Rating:
  properties:
    user:
      - NotBlank: ~
    chemical:
      - NotBlank: ~
    rating:
      - NotBlank: ~
      - Range: { min: 1, max: 5 }
    is_deleted:
      - Choice: { choices: [true, false, 1, 0] }


App\Entity\Plant:
  properties:
    name_hu:
      - Length: { max: 255 }
    name_en:
      - NotBlank: ~
      - Length: { min: 2, max: 255 }
    name_sr_Latn:
      - Length: { max: 255 }
    is_deleted:
      - Choice: { choices: [true, false, 1, 0] }


App\Entity\DroneDataPerReservation:
  properties:
    gps_coordinates:
      - NotBlank: ~
      - Regex: { pattern: '/^[-]?(([0-8]?[0-9])\.(\d+))|(90(\.0+)?);[-]?((((1[0-7][0-9])|([0-9]?[0-9]))\.(\d+))|180(\.0+)?)$/', match: false }
    results:
      - NotBlank: ~
      - Length: { min: 2, max: 5000 }
    chemical_quantity_per_ha:
      - NotBlank: ~
      - Positive: ~
    water_quantity:
      - NotBlank: ~
      - Positive: ~
    reservation:
      - NotBlank: ~
    is_deleted:
      - Choice: { choices: [true, false, 1, 0] }


App\Entity\Contact:
  properties:
    email:
      - NotBlank: ~
      - Email: ~
    message:
      - NotBlank: ~
      - Length: { min: 2, max: 5000 }
    is_deleted:
      - Choice: { choices: [true, false, 1, 0] }


App\Entity\Chemical:
  properties:
    price_per_liter:
      - NotBlank: ~
      - Positive: ~
    is_deleted:
      - Choice: { choices: [true, false, 1, 0] }
    name_hu:
      - Length: { max: 255 }
    name_en:
      - NotBlank: ~
      - Length: { min: 2, max: 255 }
    name_sr_Latn:
      - Length: { max: 255 }


App\Entity\AreaOfUseChemical:
  properties:
    plant:
      - NotBlank: ~
    chemical:
      - NotBlank: ~
