lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 300
  token_extractors:
    # check token in a cookie
    cookie:
      enabled: true
      name: BEARER
  # set_cookies:
  #   BEARER: ~
  # # Full config with defaults:
  # #  BEARER:
  # #      lifetime: null (defaults to token ttl)
  # #      samesite: lax
  # #      path: /
  # #      domain: null (null means automatically set by symfony)
  # #      secure: true (default to true)
  # #      httpOnly: true
