version: '3.7'

services:
  mariadb:
    image: mariadb
    restart: on-failure
    volumes:
      - './data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dronteh
    ports:
      - "3307:3306"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - ./apps/dronteh-api/:/usr/src/app:delegated
      - .bash_history:/root/.bash_history

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './apps/dronteh-api/:/usr/src/app:delegated'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8080:80'
    depends_on:
     - php