controllers:
  resource: ../../src/Controller/
  type: annotation

api:
  resource: ../../src/Controller/Api/
  type: annotation
  prefix: /api

admin:
  resource: ../../src/Controller/Admin/
  type: annotation
  prefix: /{_locale}/admin
  requirements:
    _locale: '%app.supported_locales%'

kernel:
  resource: ../../src/Kernel.php
  type: annotation
