controllers:
  resource: ../../src/Controller/
  type: annotation
  prefix: /{_locale}
  requirements:
    _locale: '%app.supported_locales%'

admin:
  resource: ../../src/Controller/Admin/
  type: annotation
  prefix: /{_locale}/admin
  requirements:
    _locale: '%app.supported_locales%'

kernel:
  resource: ../../src/Kernel.php
  type: annotation
